group: travis_latest

os:
  - linux
  - osx
  - windows

git:
  depth: 5

language: clojure
lein: 2.8.1

before_install:
  - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then scripts/install_clojure.sh; else scripts/install_clojure_windows.sh; fi

script:
  - lein test
  - lein install
  - cd example
  - lein run 
  - lein with-profile resolve-alias-example run
  - lein with-profile classpath-alias-example run
