group: travis_latest

os:
  - linux
  - osx
  - windows

git:
  depth: 5

language: clojure
lein: 2.8.1

before_install:
  - scripts/install_clojure.sh

script:
  - lein test
  - lein install
  - cd example
  - lein run 
  - lein with-profile resolve-alias-example run
  - lein with-profile classpath-alias-example run
